spring:
  application:
    name: foodback
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/foodback_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  tomcat:
    connection-timeout: 60000

  jackson:
    default-setter-info:
      null-value: SKIP

    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: andreev.arsenij2020@gmail.com
    password: qcqe imda tqpt fglm

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: DV62BDKJS9N2XHND7XN0210HZDM176BX7TBFUY17AZQ00WLDVNEY63VRHFVUSLBWI
  expiration:
    ms: 3_600_000
  refresh:
    expiration:
      ms: 604800000

server:
  address: 192.168.0.100
  port: 8088